[features]
seeds = false
skip-lint = false

[programs.localnet]
steal_token = "EaDhVtTXRSJrzGNkLGYsA5cQWFPwEYh1vAjF4yh7hUBP"

[programs.devnet]
steal_token = "EaDhVtTXRSJrzGNkLGYsA5cQWFPwEYh1vAjF4yh7hUBP"

[programs.mainnet]
steal_token = "EaDhVtTXRSJrzGNkLGYsA5cQWFPwEYh1vAjF4yh7hUBP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 

[toolchain]
anchor-version = "0.30.1"