[features]
seeds = false
skip-lint = false

[programs.localnet]
steal_token = "your_program_id"

[programs.devnet]
steal_token = "your_program_id"

[programs.mainnet]
steal_token = "your_program_id"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/your-username/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 